In [1]:
from tensorflow.keras.layers import TextVectorization



2025-09-28 12:52:19.174893: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [4]:
#smaple text data
text = [
    "Hello, how are you?",
    "I am fine, thank you!",
    "How about you",
    "I am good too"
]
#define the textvectorization layer
vectorizer = TextVectorization(output_mode='int', max_tokens=100,
output_sequence_length=10)

#adapt the vectorizer to the text data
vectorizer.adapt(text)

#vectorize the text data
text_vectorized = vectorizer(text)
print("vecotrized text data:\n", text_vectorized.numpy())


vecotrized text data:
 [[ 8  4 11  2  0  0  0  0  0  0]
 [ 3  5 10  7  2  0  0  0  0  0]
 [ 4 12  2  0  0  0  0  0  0  0]
 [ 3  5  9  6  0  0  0  0  0  0]]
